apiVersion: apps/v1
kind: Deployment
metadata:
  name: gql-base
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: gql-base
  template:
    metadata:
      labels:
        app: gql-base
    spec:
      containers:
      - image: GQL_BASE_IMAGE
        name: gql-base
        ports:
        - containerPort: 9001
        resources:
          limits:
            cpu: 250m
            memory: 256m
---
apiVersion: v1
kind: Service
metadata:
  name: gql-base-service
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '9001'
spec:
  selector:
    app: gql-base
  type: NodePort
  ports:
    - port: 9001
      targetPort: 9001
      name: gql-base
